

const SkillsArray = [
    { value: 'Python', label: 'Python' },
    { value: 'Java', label: 'Java' },
    { value: 'C++', label: 'C++' },
    { value: 'C', label: 'C' },
    { value: 'Javascript', label: 'Javascript' },
    { value: 'Android', label: 'Android' },
    { value: 'Artificial Intelligence', label: 'Artificial Intelligence' },
    { value: 'Angular.js', label: 'Angular.js' },
    { value: 'Assembly Language', label: 'Assembly Language' },
    { value: 'C#', label: 'C#' },
    { value: 'CSS', label: 'CSS' },
    { value: 'Databases', label: 'Databases' },
    { value: 'Django', label: 'Django' },
    { value: 'Flask', label: 'Flask' },
    { value: 'HTML', label: 'HTML' },
    { value: 'Swift', label: 'Swift' },
    { value: 'Flutter', label: 'Flutter' },
    { value: 'React Native', label: 'React Native' },
    { value: 'jQuery', label: 'jQuery' },
    { value: 'Machine Learning', label: 'Machine Learning' },
    { value: 'MATLAB', label: 'MATLAB' },
    { value: 'Octave', label: 'Octave' },
    { value: 'NumPy', label: 'NumPy' },
    { value: 'Node.js', label: 'Node.js' },
    { value: 'Perl', label: 'Perl' },
    { value: 'PHP', label: 'PHP' },
    { value: 'R', label: 'R' },
    { value: 'React.js', label: 'React.js' },
    { value: 'Ruby', label: 'Ruby' },
    { value: 'SAS', label: 'SAS' },
    { value: 'Scala', label: 'Scala' },
    { value: 'SciPy', label: 'SciPy' },
    { value: 'Scratch', label: 'Scratch' },
    { value: 'SQL', label: 'SQL' },
    { value: 'Tensorflow', label: 'Tensorflow' },
    { value: 'NoSQL', label: 'NoSQL' },
    { value: 'Vue.js', label: 'Vue.js' },
    { value: 'Web Design', label: 'Web Design' },
    { value: 'Web Development', label: 'Web Development' },
    { value: 'Wolfram Mathematica', label: 'Wolfram Mathematica' },
    { value: 'XML', label: 'XML' },
]

export default SkillsArray;